=== sonneko/sf25-site/assets/booth-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BoothTag": {
      "type": "string",
      "description": "boothTagSchema (z.enum)",
      "enum": [
        "game/experience",
        "attraction",
        "food",
        "exhibition",
        "performance",
        "movie",
        "store",
        "magazine"
      ]
    },
    "BoothColor": {
      "type": "string",
      "description": "boothColorSchema (z.enum)",
      "enum": [
        "red",
        "blue",
        "yellow_green",
        "green",
        "purple",
        "orange",
        "random"
      ]
    },
    "PlaceId": {
      "type": "string",
      "description": "placeIdSchema (z.enum)",
      "enum": [
        "gym1",
        "m1a/m1b",
        "m2a/m2b/m2c/m2d",
        "h3a",
        "h3b",
        "h3c",
        "h3d",
        "ground",
        "sp3",
        "h2b/h2c",
        "m3c",
        "m3d",
        "spj4",
        "science",
        "catholic",
        "theater",
        "biology",
        "h2d",
        "sp2",
        "h1c/h1d",
        "tech",
        "sp5",
        "h2a",
        "sp4",
        "physics",
        "h3e",
        "music",
        "large/sp1",
        "m3b",
        "?",
        "sp6",
        "gym2",
        "m1c/m1d",
        "meeting",
        "shodo",
        "m3a"
      ]
    }
  },
  "type": "object",
  "title": "Booth",
  "description": "boothSchema (z.object)",
  "required": [
    "booth_id",
    "booth_name",
    "short_description",
    "long_description",
    "tags",
    "color",
    "has_cm",
    "has_website",
    "group_name",
    "place_id",
    "place",
    "overview"
  ],
  "properties": {
    "booth_id": {
      "type": "string"
    },
    "booth_name": {
      "type": "string"
    },
    "short_description": {
      "type": "string"
    },
    "long_description": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/BoothTag"
      }
    },
    "color": {
      "$ref": "#/definitions/BoothColor"
    },
    "has_cm": {
      "type": "boolean"
    },
    "has_website": {
      "type": "boolean"
    },
    "group_name": {
      "type": "string"
    },
    "place_id": {
      "$ref": "#/definitions/PlaceId"
    },
    "place": {
      "type": "string"
    },
    "overview": {
      "type": "string"
    },
    "not-cpmplete": {
      "type": "boolean"
    }
  },
  "additionalProperties": false
}

=== sonneko/sf25-site/assets/booths/club-12.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-12",
  "booth_name": "星光グラフ",
  "short_description": "部員撮影の写真の展示とグッズ販売、50枚限定の合格祈願チェキ撮影会を行います。ぜひお越しください！",
  "long_description": "写真部ではさまざまな趣味を持つ部員が撮影した写真の展示やカレンダー、ステッカーなどの物販、50枚限定の合格祈願チェキの撮影会(無くなり次第終了)を行います。写真の魅力を多彩に楽しめるブースへ是非お越しください！",
  "tags": ["exhibition", "store"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "写真部",
  "place_id": "spj4",
  "place": "中学４F特別",
  "overview": "写真展示・販売・撮影"
}

=== sonneko/sf25-site/assets/booths/class-m3b.json
{
  "booth_id": "class-m3b",
  "booth_name": "フリースロー",
  "short_description": "ボールを投げて、ゴールを狙おう！近距離・中距離・遠距離の3つの距離から選べます。入った数に応じて景品があるよ。来てね",
  "long_description": "バスケが得意じゃなくても大丈夫！近距離・中距離・遠距離の3つの距離から選べます。気軽にボールを投げてゴールを狙ってみよう！入った数に応じて景品も用意しているよ。ぜひ気軽に立ち寄ってチャレンジしてみてね。お待ちしています！",
  "tags": ["game/experience"],
  "color": "random",
  "has_cm": true,
  "has_website": true,
  "group_name": "M3B",
  "place_id": "h3b",
  "place": "H3B",
  "overview": "フリースロー"
}

=== sonneko/sf25-site/assets/booths/club-10.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-10",
  "booth_name": "んけうすproject2025",
  "short_description": "毎年恒例の部員が作ったゲームを販売する企画です。無料でも遊べるので、ぜひ寄って行ってください！※今年は数学はありません。",
  "long_description": "部員が作ったＰＣゲームを遊べます！！アクションゲームとかバトルシミュレーターゲームとかあります！！ＣＤを買えば家でも遊べます！！（激安）楽しいはずなので来てください！！！…え？数学の問題を解く企画は？チョットナニイッテルカワカラナイデス…",
  "tags": ["game/experience", "store", "magazine"],
  "color": "blue",
  "has_cm": true,
  "has_website": true,
  "group_name": "数学研究部",
  "place_id": "m3c",
  "place": "M3C",
  "overview": "PCゲームの展示販売"
}

=== sonneko/sf25-site/assets/booths/volu-17.json
{
    "booth_id": "volu-17",
    "booth_name": "星光生ラップバトル選手権",
    "short_description": "星光生のなんたるか。それは歌詞にない本心を歌う時に現れる。上原先生含む4MCの即興ラップで会場沸騰待ったなし！！",
    "long_description": "文化祭初企画！即興ラップバトル開催！リズムに乗せた言葉とフローが交差し、瞬間ごとに新たな表現が飛び出す。誰がどんな言葉で場を沸かすのかが醍醐味！観客の皆さん全員の挙手と声援で勝敗を決する唯一無二の熱きステージを体感せよ！",
    "tags": [
        "performance"
    ],
    "color": "random",
    "has_cm": false,
    "has_website": true,
    "group_name": "星光生ラップ選手権",
    "place_id": "gym1",
    "place": "講堂",
    "overview": "ラップ(バンド)"
}

=== sonneko/sf25-site/assets/booths/class-h2b.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "class-h2b",
  "booth_name": "空中鞦韆",
  "short_description": "企画名よめましたか？空中ブランコ、そうあの空中ブランコです！クラス一丸で作り上げた空中ブランコ。是非乗ってみてください！",
  "long_description": "名前の漢字、読み方わかりましたか？これは空中ブランコ、そうあの空中ブランコです！これは怖さ控えめ空中ブーランコ。見た目はショボいと思うかもしれない」でもクラス一丸で作った空中ブランコ！ぜひこの機会に乗ってみては？",
  "tags": ["attraction"],
  "color": "yellow_green",
  "has_cm": false,
  "has_website": true,
  "group_name": "H2B",
  "place_id": "sp3",
  "place": "特３",
  "overview": "空中ブランコ"
}

=== sonneko/sf25-site/assets/booths/club-08.json
{
    "booth_id": "club-08",
    "booth_name": "たこやき",
    "short_description": "高校バスケ部が作る、外はカリカリ、中はふわふわのたこ焼き！ほっぺが落ちるほどの美味しさです。ぜひ、来てね",
    "long_description": "高校バスケ部が作る、外はカリカリ、中はふわふわのたこ焼き！ほっぺが落ちるほどの美味しさで、その破壊力はまるで八村塁のダンクのよう。6個で200円という手頃に買える値段なので、ぜひ食べに来てください！！",
    "tags": [
        "food"
    ],
    "color": "random",
    "has_cm": false,
    "has_website": true,
    "group_name": "高校バスケ部",
    "place_id": "ground",
    "place": "グラウンド",
    "overview": "たこ焼き"
}

=== sonneko/sf25-site/assets/booths/grade-2b.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "grade-2b",
  "booth_name": "75Kといっしょ",
  "short_description": "私達中2は、ゲームコーナー、迷路、中2が小学生に教える体験授業の3つをします！文武両道といえばここしか勝たん！ぜひ来てください！",
  "long_description": "私達中2は、3つの企画をやります。1つ目はみんな楽しいゲームコーナー、2つ目は選ばれし者たちが作った迷路、そして3つ目は中2が小学生に教える体験授業です！文武両道といえばここしか勝たん！ぜひ来てください！",
  "tags": ["game/experience", "performance", "store"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "中２学年",
  "place_id": "m2a/m2b/m2c/m2d",
  "place": "M2A,M2B,M2C,M2D",
  "overview": "迷路、ゲーム、授業"
}

=== sonneko/sf25-site/assets/booths/club-07.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-07",
  "booth_name": "ほっけいぽていと",
  "short_description": "ホッケー部の作る外カリ中ほくの超美味しいフライドポテトを\\nぜひ皆さん食べに来てください！グラウンドで待ってます！",
  "long_description": "ホッケー部の作る外カリ中ほくの超美味しいフライドポテト。塩とケチャャッぷの他にも様々な味付けを用意しています！コスパ最高で気に入ってもらえる事間違い無しです！\\nぜひ皆さん食べに来てくださいね♪グラウンドで待ってます！",
  "tags": ["food"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "ホッケー部",
  "place_id": "ground",
  "place": "グラウンド",
  "overview": "フライドポテト"
}
