=== sonneko/sf25-site/assets/booth-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BoothTag": {
      "type": "string",
      "description": "boothTagSchema (z.enum)",
      "enum": [
        "game/experience",
        "attraction",
        "food",
        "exhibition",
        "performance",
        "movie",
        "store",
        "magazine"
      ]
    },
    "BoothColor": {
      "type": "string",
      "description": "boothColorSchema (z.enum)",
      "enum": [
        "red",
        "blue",
        "yellow_green",
        "green",
        "purple",
        "orange",
        "random"
      ]
    },
    "PlaceId": {
      "type": "string",
      "description": "placeIdSchema (z.enum)",
      "enum": [
        "gym1",
        "m1a/m1b",
        "m2a/m2b/m2c/m2d",
        "h3a",
        "h3b",
        "h3c",
        "h3d",
        "ground",
        "sp3",
        "h2b/h2c",
        "m3c",
        "m3d",
        "spj4",
        "science",
        "catholic",
        "theater",
        "biology",
        "h2d",
        "sp2",
        "h1c/h1d",
        "tech",
        "sp5",
        "h2a",
        "sp4",
        "physics",
        "h3e",
        "music",
        "large/sp1",
        "m3b",
        "?",
        "sp6",
        "gym2",
        "m1c/m1d",
        "meeting",
        "shodo",
        "m3a"
      ]
    }
  },
  "type": "object",
  "title": "Booth",
  "description": "boothSchema (z.object)",
  "required": [
    "booth_id",
    "booth_name",
    "short_description",
    "long_description",
    "tags",
    "color",
    "has_cm",
    "has_website",
    "group_name",
    "place_id",
    "place",
    "overview"
  ],
  "properties": {
    "booth_id": {
      "type": "string"
    },
    "booth_name": {
      "type": "string"
    },
    "short_description": {
      "type": "string"
    },
    "long_description": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/BoothTag"
      }
    },
    "color": {
      "$ref": "#/definitions/BoothColor"
    },
    "has_cm": {
      "type": "boolean"
    },
    "has_website": {
      "type": "boolean"
    },
    "group_name": {
      "type": "string"
    },
    "place_id": {
      "$ref": "#/definitions/PlaceId"
    },
    "place": {
      "type": "string"
    },
    "overview": {
      "type": "string"
    },
    "not-cpmplete": {
      "type": "boolean"
    }
  },
  "additionalProperties": false
}

=== sonneko/sf25-site/assets/booths/volu-07.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "volu-07",
  "booth_name": "惑惑文藝部～綺談遊戯に集うものたち～",
  "group_name": "文芸部",
  "place_id": "h3e",
  "overview": "短編映画",
  "place": "H3E",
  "long_description": "中世の劇作家が愛したアナログゲームを開催中！勝てば豪華景品がもらえるかも！？文芸部員が書き下ろした部誌も販売中です！",
  "short_description": "中世の劇作家が愛したアナログゲームを開催中！勝てば豪華景品がもらえるかも！？文芸部員が書き下ろした部誌も販売中です！",
  "color": "random",
  "has_cm": false,
  "has_website": false,
  "tags": ["game/experience", "store", "movie", "magazine"]
}

=== sonneko/sf25-site/assets/booths/class-h2d.json
{
  "booth_id": "class-h2d",
  "booth_name": "麺屋　あなたとまざりたいんです",
  "short_description": "断言します。老若男女問わず、これを食べたあなたは絶対癖になる。個性が強すぎるみんなで作った至極の一杯をぜひご賞味あれ。",
  "long_description": "個性が強すぎるメンバーでタレを作ったら、すんごいうまいタレができちゃいました！トッピングが豊富すぎて、これには他のラーメン屋もびっくり！？食べる時はよく混ぜてくださいね。さあ僕たちと一緒にまざりましょう。",
  "tags": ["food"],
  "color": "orange",
  "has_cm": false,
  "has_website": true,
  "group_name": "H2D",
  "place_id": "ground",
  "place": "グラウンド",
  "overview": "まぜそば"
}

=== sonneko/sf25-site/assets/booths/grade-1a.json
{
  "booth_id": "grade-1a",
  "booth_name": "中1合唱",
  "short_description": "この日のためにクラス一丸となって練習してきました。私たちの歌声が、聴いてくださる皆さんの心に温かく響きますように。",
  "long_description": "初めてのスクールフェア、中学1年生が心を込めて合唱をお届けします。この日のためにクラス一丸となって練習してきました。私たちの歌声が、聴いてくださる皆さんの心に温かく響きますように。精一杯の歌いたいと思います！",
  "tags": ["performance"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "中１合唱",
  "place_id": "gym1",
  "place": "講堂",
  "overview": "合唱"
}

=== sonneko/sf25-site/assets/booths/club-25.json
{
  "booth_id": "club-25",
  "booth_name": "スーパーボールすくい",
  "short_description": "那須与一は一矢で敵船の扇を射抜いてみせたと言われます。この企画も、あなたの胸の内をひょうと射抜いて見せましょう。",
  "long_description": "\"好く\"人は\"好く\"スーパーボール\"すく\"いというやつです。SF （\"スク\"ールフェア）に\"巣食\"うスーパーボール屋に集い\"すくすく\"売り上げを成長させて店員の出資金を\"救\"いましょう。すくったボールは\"すぐ\"お持ち帰りいただけます。胸の\"空く\"ような思い出を貴方に。\\n※字数については連絡欄参照",
  "tags": ["game/experience"],
  "color": "random",
  "has_cm": true,
  "has_website": true,
  "group_name": "弓道部",
  "place_id": "ground",
  "place": "グラウンド",
  "overview": "スーパーボールすくい"
}

=== sonneko/sf25-site/assets/booths/club-30.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-30",
  "booth_name": "合唱部",
  "group_name": "合唱部",
  "place": "音楽室",
  "place_id": "music",
  "overview": "合唱",
  "color": "random",
  "has_cm": false,
  "has_website": false,
  "tags": ["performance"],
  "long_description": "放課後、教室に響く熱唱の声。青春の汗と魂がここにある——奇跡の美声、開演！音楽室でお待ちしております！！！！！！！！",
  "short_description": "放課後、教室に響く熱唱の声。青春の汗と魂がここにある——奇跡の美声、開演！音楽室でお待ちしております！！！！！！！！"
}

=== sonneko/sf25-site/assets/booths/volu-19.json
{
  "$schema": "../booth-schema.json",
  "color": "red",
  "booth_id": "volu-19",
  "long_description": "バイオリンを2人で演奏します！演奏する曲は2つのバイオリンのための協奏曲です。息ぴったりの演奏をぜひ聴きに来てください！まるで会話しているかのように聞こえる、バイオリンの掛け合いの部分が最高の聞きどころです。",
  "short_description": "バイオリンを2人で演奏します！息ぴったりの演奏をぜひ聴きに来てください！弾く曲は、二つのバイオリンのための協奏曲です。",
  "tags": [],
  "has_website": false,
  "has_cm": false,
  "booth_name": "Violingual",
  "group_name": "福富・鈴木によるバイオリンスペシャルコンサート",
  "overview": "バイオリン",
  "place_id": "music",
  "place": "音楽室"
}

=== sonneko/sf25-site/assets/booths/club-22.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-22",
  "booth_name": "囲碁将棋部",
  "short_description": "※囲碁はありません。部員との対局(50円)、部誌の販売(50円)を行っています。将棋を指したい方は是非お立ち寄りください",
  "long_description": "※囲碁はありません！部員との対局はもちろん、部員が製作した部誌も販売しています。腕に自信がある人も、初心者の方も大歓迎です！少しでも興味のある方は、是非囲碁将棋部へお越しください！高校棟三階、高二Aの教室でお待ちしております。",
  "tags": ["game/experience", "magazine"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "囲碁将棋部",
  "place_id": "h2a",
  "place": "H2A",
  "overview": "将棋"
}

=== sonneko/sf25-site/assets/booths/volu-18.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "volu-18",
  "booth_name": "K-コジバンド",
  "short_description": "K-コジバンドは某数学教師のロマンチックなピアノに高2のサックスとヴァイオリンが加わった心安らぐ曲を奏でるつもりです。",
  "long_description": "こんにちは。K-コジバンドです。このバンドは某数学教師のK先生と仲良しな72Kの音楽担当2人が組んだトリオバンドです。T-saxとヴァイオリンとピアノで誰もが聞いたことのある曲を演奏します。生徒と教師の織り成すハーモニーをお楽しみください！",
  "tags": [
    "performance"
  ],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "先生と生徒のジャズ",
  "place_id": "gym1",
  "place": "講堂",
  "overview": "ジャズ演奏(バンド)"
}
