=== sonneko/sf25-site/assets/booth-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BoothTag": {
      "type": "string",
      "description": "boothTagSchema (z.enum)",
      "enum": [
        "game/experience",
        "attraction",
        "food",
        "exhibition",
        "performance",
        "movie",
        "store",
        "magazine"
      ]
    },
    "BoothColor": {
      "type": "string",
      "description": "boothColorSchema (z.enum)",
      "enum": [
        "red",
        "blue",
        "yellow_green",
        "green",
        "purple",
        "orange",
        "random"
      ]
    },
    "PlaceId": {
      "type": "string",
      "description": "placeIdSchema (z.enum)",
      "enum": [
        "gym1",
        "m1a/m1b",
        "m2a/m2b/m2c/m2d",
        "h3a",
        "h3b",
        "h3c",
        "h3d",
        "ground",
        "sp3",
        "h2b/h2c",
        "m3c",
        "m3d",
        "spj4",
        "science",
        "catholic",
        "theater",
        "biology",
        "h2d",
        "sp2",
        "h1c/h1d",
        "tech",
        "sp5",
        "h2a",
        "sp4",
        "physics",
        "h3e",
        "music",
        "large/sp1",
        "m3b",
        "?",
        "sp6",
        "gym2",
        "m1c/m1d",
        "meeting",
        "shodo",
        "m3a"
      ]
    }
  },
  "type": "object",
  "title": "Booth",
  "description": "boothSchema (z.object)",
  "required": [
    "booth_id",
    "booth_name",
    "short_description",
    "long_description",
    "tags",
    "color",
    "has_cm",
    "has_website",
    "group_name",
    "place_id",
    "place",
    "overview"
  ],
  "properties": {
    "booth_id": {
      "type": "string"
    },
    "booth_name": {
      "type": "string"
    },
    "short_description": {
      "type": "string"
    },
    "long_description": {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/BoothTag"
      }
    },
    "color": {
      "$ref": "#/definitions/BoothColor"
    },
    "has_cm": {
      "type": "boolean"
    },
    "has_website": {
      "type": "boolean"
    },
    "group_name": {
      "type": "string"
    },
    "place_id": {
      "$ref": "#/definitions/PlaceId"
    },
    "place": {
      "type": "string"
    },
    "overview": {
      "type": "string"
    },
    "not-cpmplete": {
      "type": "boolean"
    }
  },
  "additionalProperties": false
}

=== sonneko/sf25-site/assets/booths/volu-15.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "volu-15",
  "booth_name": "漫才Ⅲ",
  "short_description": "今年3年目の漫才！去年は多数出場し一番の盛り上がりを見せました。そして今回も更に進化させてお届けします！是非！！",
  "long_description": "星光での漫才の歴史は浅く、今年で3年目！しかし、歴史など関係ありません。去年は講堂企画では一番の盛り上がりを見せました。そんな中で今年は更にレベルアップしてお届けします。去年の優勝者も参加するハイレベルな戦い間違いなし！絶対来てな！！",
  "tags": ["performance"],
  "color": "random",
  "has_cm": true,
  "has_website": true,
  "group_name": "漫才Ⅲ",
  "place_id": "gym1",
  "place": "講堂",
  "overview": "漫才"
}

=== sonneko/sf25-site/assets/booths/volu-04.json
{
    "booth_id": "volu-04",
    "booth_name": "漢字テスト",
    "short_description": "星光生の漢字力に挑戦！レベル分けされているので老若男女幅広い世代が楽しめます。漢字力に自信のある人はぜひお越しを。",
    "long_description": "SFも遊んでばかりではいられない。受験を視野に入れている人や、漢字力に自信のある人は星光生の漢字力に挑戦してみよう。レベル分けされているので、老若男女幅広い世代が楽しめます。空いた時間に是非お越しを。",
    "tags": [
        "exhibition",
        "store"
    ],
    "color": "random",
    "has_cm": false,
    "has_website": true,
    "group_name": "言語同好会(日本語班)",
    "place_id": "?",
    "place": "一般教室",
    "overview": "漢字テスト"
}

=== sonneko/sf25-site/assets/booths/volu-05.json
{
    "booth_id": "volu-05",
    "booth_name": "謎グルイ",
    "short_description": "ここで開催される様々な「ゲーム」には「必勝法」がある。至高のひらめきで謎を解き明かし、難攻不落のゲームを打ち破れ！",
    "long_description": "ここでは様々なゲームが開催されています。きっと一筋縄ではクリアすることが出来ないでしょう。そこで、「謎解き」をご用意いたしました。謎を解けばクリアするための手がかりが手に入ります。ぜひ、あなたのひらめきでゲームクリアを目指してください。",
    "tags": [
        "game/experience",
        "store"
    ],
    "color": "red",
    "has_cm": true,
    "has_website": true,
    "group_name": "AH!Astery",
    "place_id": "sp6",
    "place": "特6",
    "overview": "謎解き"
}

=== sonneko/sf25-site/assets/booths/club-26.json
{
  "booth_id": "club-26",
  "booth_name": "PK",
  "short_description": "他のところとは比べ物にならない超豪華景品の数々！！！あなたはサッカー部相手に何点決められる？？ぜひお待ちしています！",
  "long_description": "他のところとは比べ物にならない超豪華景品の数々！！！あなたはサッカー部相手に何点決められる？？ぜひ一度腕試しにお越しください！！\\n高校棟第2体育館でサッカー部の占いのもおすすめで〜す。ぜひお越しくださいまし～",
  "tags": ["game/experience"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "サッカー部",
  "place_id": "ground",
  "place": "グラウンド",
  "overview": "PK"
}

=== sonneko/sf25-site/assets/booths/grade-2a.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "grade-2a",
  "booth_name": "中2合唱",
  "short_description": "中2のクラス合唱です。合宿や音楽の授業、LHRで練習しました。ボーイソプラノや男性ならではの低音をお楽しみください！",
  "long_description": "中学2年生もクラス合唱をやります。山荘や南部学舎、音楽の授業、LHRの時間を使って練習しました。美しいボーイソプラノや頼りがいのある低音が見どころとなっています。ぜひお立ち寄りいただき、楽しんでいってください！お待ちしております。",
  "tags": [
    "performance"
  ],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "中２合唱",
  "place_id": "gym1",
  "place": "講堂",
  "overview": "合唱"
}

=== sonneko/sf25-site/assets/booths/club-31.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-31",
  "booth_name": "吹奏楽定期演奏会",
  "group_name": "吹奏楽部",
  "overview": "演奏会",
  "place": "音楽室",
  "place_id": "music",
  "long_description": "今年は午前がピアノ、午後が合奏となっています。どちらも有名なアニソンやポップスを選曲したので休憩がてらにお越し下さい。",
  "short_description": "今年は午前がピアノ、午後が合奏となっています。どちらも有名なアニソンやポップスを選曲したので休憩がてらにお越し下さい。",
  "color": "random",
  "has_cm": false,
  "has_website": false,
  "tags": ["performance"]
}

=== sonneko/sf25-site/assets/booths/club-02.json
{
  "booth_id": "club-02",
  "booth_name": "いてまえ焼きそば",
  "short_description": "香ばしいソースの香りと迫力あるある鉄板さばきで、お腹も心も満たされること間違いなし！是非足を運んでみてください。",
  "long_description": "今日はグラウンドじゃなく鉄板で勝負だ！活気あふれる野球部が、熱気いっぱいに焼きそばをお届けします。香ばしいソースの香りと迫力ある鉄板さばきで、お腹も心も満たされること間違いなし。ぜひ足を運んでみてください！",
  "tags": ["food"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "高校野球部",
  "place_id": "ground",
  "place": "グラウンド",
  "overview": "やきそば"
}

=== sonneko/sf25-site/assets/booths/club-23.json
{
  "$schema": "../booth-schema.json",
  "booth_id": "club-23",
  "booth_name": "みんなで早押し&ペーパークイズ",
  "short_description": "高校生クイズ2025準決勝進出。ペーパークイズと早押しクイズを無料でやってます。高校生クイズ体験記込みの部誌は50円。",
  "long_description": "高校生クイズ2025準決勝進出の実績ある部活です。ペーパークイズと早押しクイズを無料でやってます。今までに身につけた知識を最大限に活用して、問題を攻略しましょう！初心者大歓迎です！部誌には高校生クイズ体験記を書いてます。50円。",
  "tags": ["game/experience", "magazine"],
  "color": "random",
  "has_cm": false,
  "has_website": true,
  "group_name": "クイズ研究会",
  "place_id": "sp4",
  "place": "特４",
  "overview": "クイズ"
}
